### ISSUE TITLE
Lançar este projeto no google play store?

### ISSUE THREAD

**Issue by thisiscleverson** [coffee-is-power/tabnews-mobile#3]
Olá amigo, eu queria saber se você pretende lançar esse projeto no google play store?

**Comment by coffeeispower** [comment]
Me dá 10 dólares e eu posto.

**Comment by thisiscleverson** [comment]
Infelismente não tenho esse recurso ao meu alcance.

**Comment by coffeeispower** [comment]
E só por isso mesmo, não tem outro motivo se não já teria postado.
